LOCAL_PATH := $(call my-dir)
include $(DD_CLEAR)
DD_PRODUCT := H8S
DD_KERNEL := $(LOCAL_PATH)/kernel

DD_KERNEL_BASE := 0x60400000
DD_KERNEL_PAGESIZE := 16384
DD_KERNEL_CMDLINE := 
DD_RAMDISK_OFFSET := 0x01c00000
DD_TAGS_OFFSET := 0xffffffffffffffff
DD_DEVICE_SCREEN_TYPE := "XHDPI"

DD_PRODUCT_ROOT := $(LOCAL_PATH)/root
DD_DEVICE_CONFIG := $(LOCAL_PATH)/*.conf
include $(DD_RECOVERY)
